### ISSUE TITLE
Question/Enhancement: Support for NRF52x devices?

### ISSUE THREAD

**Issue by TMRh20** [Hobietime/RF24G#3]
I was considering submitting a PR for this, but figured it would be worth asking if there is any interest in supporting the new NRF52x devices in this library.

I've written a new library [nrf_to_nrf](https://github.com/TMRh20/nrf_to_nrf) that works with the new radios for NRF52x to NRF24L01 communication, so it works much the same way, using the same API as the RF24 library, and this library would simplify its usage the same as with RF24, except there could be up to 8 devices connected, sending packets up to 127 bytes long if desired.

**Comment by Hobietime** [comment]
Hello. I would be happy to support this! 

How would you recommend setting up support for the library? 

As far as I can tell it would just be changing a few constants and dependencies in the header file.

If that is the case it should be doable with some simple #define logic.

From what I just read, this allows for interoperability between the two radios as well. If that is the case, do the limits fall back to 6 devices and 32 bytes?

Caio

**Comment by TMRh20** [comment]
Well I guess there are two approaches, with defines it’s simpler but typically would limit users to either RF24 or nrf_to_nrf. We could also use c++ templates which would allow users to use both libs simultaneously.
For simplicity for both users and us I would assume you would want to go with defines.
For a mixed network, yes we are still limited to 6 pipes and 32 bytes.
Just let me know how u would like to proceed and I can see about putting together a PR
